name: Build & Release Suricata Rules

on:
  push:               # 每次 push 就重打
    branches: [ main ]
  workflow_dispatch:  # GitHub UI 可手動觸發

permissions:
  contents: write     # 允許 Action 更新 Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pack *.rules → tar.gz
        run: tar -czf customrules.tar.gz rules

      - name: Publish / Update "latest" Release
        uses: softprops/action-gh-release@v2        # 官方 Action
        with:                                       # 關鍵參數
          tag_name: latest
          name: Suricata Custom Rules
          files: customrules.tar.gz                 # 要附加的檔案
          make_latest: true
